"""Reference French commune/department/region/country place hierarchy,
bundled as `data/france_places.json` (generated by
`scripts/convert_places_reference.py` from
https://www.histoiredeserignan.fr/downloads/genealogy/lieux.gramps).

`gramps_writer.py` uses this to build its place hierarchy with the exact
same `handle`/`id` values as the reference file, so an ExportGeneanet
.gramps file merges cleanly into a Gramps database that already imported
it, instead of creating a duplicate parallel place tree.

Matching is deliberately conservative: only French places actually present
in the reference data resolve to the full City->Department->Region->Country
chain; anything else (a foreign place, or a French commune this reference
happens not to have) at best resolves to just its Country, and otherwise
resolves to nothing — `gramps_writer.py` is responsible for building fresh,
new-handle place nodes from the raw text in that case, not this module.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources


@dataclass(frozen=True)
class PlaceNode:
    handle: str
    id: str
    type: str  # "City" | "District" | "Department" | "Region" | "Country"
    name: str
    code: str


_POSTCODE_RE = re.compile(r"^\d{4,5}$")


def _casefold(text: str) -> str:
    return text.strip().casefold()


@lru_cache(maxsize=1)
def _load_nodes() -> dict[str, dict]:
    raw = resources.files("exportgeneanet.data").joinpath("france_places.json").read_text(encoding="utf-8")
    return json.loads(raw)


@lru_cache(maxsize=1)
def _city_index() -> dict[tuple[str, str], str]:
    """`(casefolded city name, casefolded department name) -> city handle`.
    Department is required to disambiguate: 1,452 of the reference file's
    34,955 city names aren't unique on their own (e.g. "Selles" names 4
    different communes in 4 different departments)."""
    index: dict[tuple[str, str], str] = {}
    for handle, node in _load_nodes().items():
        if node["type"] != "City" or not node["parent"]:
            continue
        parent = _load_nodes().get(node["parent"])
        if parent is None or parent["type"] != "Department":
            continue
        index[(_casefold(node["name"]), _casefold(parent["name"]))] = handle
    return index


@lru_cache(maxsize=1)
def _country_index() -> dict[str, str]:
    return {
        _casefold(node["name"]): handle for handle, node in _load_nodes().items() if node["type"] == "Country"
    }


def chain_for(handle: str) -> list[PlaceNode]:
    """`handle` and every ancestor, root (Country) first, leaf last —
    ready to emit as a chain of Gramps `<placeobj>` records linked by
    `<placeref>`."""
    nodes = _load_nodes()
    chain: list[PlaceNode] = []
    current: str | None = handle
    seen: set[str] = set()
    while current is not None and current not in seen:
        seen.add(current)
        node = nodes.get(current)
        if node is None:
            break
        chain.append(
            PlaceNode(handle=current, id=node["id"], type=node["type"], name=node["name"], code=node["code"])
        )
        current = node["parent"]
    chain.reverse()
    return chain


def resolve(raw_place_text: str | None) -> list[PlaceNode]:
    """Parse a Geneanet place string and resolve it against the reference
    hierarchy, root-first (`chain_for`'s order).

    Handles the two confirmed real Geneanet formats: `"City, Department,
    Region, Country"` and, when a postcode is present, `"City, Postcode,
    Department, Region, COUNTRY"` (the postcode segment — a bare 4-5 digit
    group — is dropped, never matched against or represented in the
    result; there is no postcode level in the reference hierarchy either).
    A `"Locality - City"` first segment keeps only the part after the last
    " - ". Country casing is normalized (`"France"`/`"FRANCE"` both match).

    Returns `[]` if `raw_place_text` is empty or nothing at all matches;
    returns just a `[Country]` chain if only the country segment matches
    (e.g. a foreign place, or a French commune missing from the reference
    data); returns the full chain on a city match.
    """
    if not raw_place_text:
        return []

    segments = [s.strip() for s in raw_place_text.split(",")]
    segments = [s for s in segments if s and not _POSTCODE_RE.fullmatch(s)]
    if not segments:
        return []

    city_name = segments[0].rsplit(" - ", 1)[-1].strip()
    department_raw = segments[1] if len(segments) >= 3 else None
    country_raw = segments[-1] if len(segments) > 1 else None

    if department_raw:
        handle = _city_index().get((_casefold(city_name), _casefold(department_raw)))
        if handle:
            return chain_for(handle)

    if country_raw:
        handle = _country_index().get(_casefold(country_raw))
        if handle:
            return chain_for(handle)

    return []
